### ISSUE TITLE
Sim-c and test-suite gets deleted on running tests

### ISSUE THREAD

**Issue by sayandip18** [cimplec/test-suite#1]
On cloning the test-suite and running `simc-test`, both the cloned repositories (sim-c and test-suite) on my system got deleted all of a sudden.
 
 **To Reproduce**

 1. Clone the sim-c repo

 2. Install the test-suite.

 3. Run `simc-test`
 
4. You'll see that both the sim-c repository and the test-suite repository are no longer there in your system.

 **Expected behavior**
 Neither of the repos should get deleted.
 
  OS: Linux

**Comment by frankhart2018** [comment]
Fixed and pushed
